### ISSUE TITLE
Game Crashes

### ISSUE THREAD

**Issue by KirboC** [codeshaunted/monke#9] opened 2022-09-07 12:08 UTC
BTD6 seems to crash whenever the compiled Profile.Save is put in the save directory.

I removed everything from the save directory, signed in and had an option between the local save and the cloud save. The game crashes when choosing the local save with the compiled Profile.Save.

It decompiles fine and I use Notepad++ to edit the text. I changed one number on a monkey's XP to test it and it still crashes.

I even left the text unformatted, changed one number and it still crashed. It just rolls back to the cloud save no matter the change.

**Comment by ConBlaze** [comment] 2022-09-08 23:53
Having the same issue although when you use a natural save or my friends it still works and doesn't crash or reload, could be from our end or that It is now server-sided.

**Comment by ghost** [comment] 2022-09-09 00:08
This has been a problem for a few months now, the fix is to disconnect from the internet the first time you put the re-compiled Profile.Save file into the folder. Once in the folder load up BTD6 and you'll notice it will load just fine. Exit the game then reconnect to the internet, then reopen BTD6 and it should work just fine, no crashing. You can even use the "Backup" function to back up the new save to the cloud.

**Comment by codeshaunted** [comment] 2022-09-09 00:46
> This has been a problem for a few months now, the fix is to disconnect from the internet the first time you put the re-compiled Profile.Save file into the folder. Once in the folder load up BTD6 and you'll notice it will load just fine. Exit the game then reconnect to the internet, then reopen BTD6 and it should work just fine, no crashing. You can even use the "Backup" function to back up the new save to the cloud.

Do you think this is some new security measure that’s been put in place? If someone can confirm that this works, definitely make a PR for the README.

**Comment by ConBlaze** [comment] 2022-09-09 00:58
> 

I tried and I can confirm it that it worked

**Comment by ghost** [comment] 2022-09-09 20:21
> > This has been a problem for a few months now, the fix is to disconnect from the internet the first time you put the re-compiled Profile.Save file into the folder. Once in the folder load up BTD6 and you'll notice it will load just fine. Exit the game then reconnect to the internet, then reopen BTD6 and it should work just fine, no crashing. You can even use the "Backup" function to back up the new save to the cloud.
> 
> Do you think this is some new security measure that’s been put in place? If someone can confirm that this works, definitely make a PR for the README.

I'm not 100% sure, but I did notice that when monke re-compiles saves it doesn't look the same as the way BTD6 compiles saves. If I have a de-compiled save that's around 100kb, monke will re-compile back down to around 70kb. But when you do the network trick and open BTD6 and then close it the file somehow gets compressed further down to 47kb. I think what's happening is that when you're connected to the internet it's trying to display the menu where you can choose whether you want to select your cloud save or the "On-device" save, but it can't because it thinks the On-device save is corrupted, so it just crashes the game.

Also I'm not sure if this is a fault of your program but the lines in the save don't get indented correctly when decompiling the save. This website https://www.saveeditonline.com/ can indent the save file for you, which is really nice. It would be nice if you could somehow find a way for monke to indent the files correctly.

**Comment by codeshaunted** [comment] 2022-09-09 22:19
> > > This has been a problem for a few months now, the fix is to disconnect from the internet the first time you put the re-compiled Profile.Save file into the folder. Once in the folder load up BTD6 and you'll notice it will load just fine. Exit the game then reconnect to the internet, then reopen BTD6 and it should work just fine, no crashing. You can even use the "Backup" function to back up the new save to the cloud.
> > 
> > 
> > Do you think this is some new security measure that’s been put in place? If someone can confirm that this works, definitely make a PR for the README.
> 
> I'm not 100% sure, but I did notice that when monke re-compiles saves it doesn't look the same as the way BTD6 compiles saves. If I have a de-compiled save that's around 100kb, monke will re-compile back down to around 70kb. But when you do the network trick and open BTD6 and then close it the file somehow gets compressed further down to 47kb. I think what's happening is that when you're connected to the internet it's trying to display the menu where you can choose whether you want to select your cloud save or the "On-device" save, but it can't because it thinks the On-device save is corrupted, so it just crashes the game.
> 
> Also I'm not sure if this is a fault of your program but the lines in the save don't get indented correctly when decompiling the save. This website https://www.saveeditonline.com/ can indent the save file for you, which is really nice. It would be nice if you could somehow find a way for monke to indent the files correctly.

I'm fairly sure this size difference is due to me cranking the compression level all the way up to the max. The JSON isn't indented "correctly" because that's how the game saves it, without any unnecessary whitespace, I probably won't be auto formatting it as I want the output to be accurate to the exact bytes that the game compressed.

**Comment by KirboC** [comment] 2022-09-10 09:50
> This has been a problem for a few months now, the fix is to disconnect from the internet the first time you put the re-compiled Profile.Save file into the folder. Once in the folder load up BTD6 and you'll notice it will load just fine. Exit the game then reconnect to the internet, then reopen BTD6 and it should work just fine, no crashing. You can even use the "Backup" function to back up the new save to the cloud.

I use a "steam connected" account as opposed to an NK account. Not sure if the difference matters or not. I also tried the disconnecting internet method and it still crashes before the "choose a save" menu shows up. Not sure what you did specifically.

 I had an old steam connected account and deleted it since it was flagged. The old one seemed to work with modifications regardless and never crashed. Not sure if newer accounts have a different "measure" so to speak.

**Comment by codeshaunted** [comment] 2022-09-10 20:21
> > This has been a problem for a few months now, the fix is to disconnect from the internet the first time you put the re-compiled Profile.Save file into the folder. Once in the folder load up BTD6 and you'll notice it will load just fine. Exit the game then reconnect to the internet, then reopen BTD6 and it should work just fine, no crashing. You can even use the "Backup" function to back up the new save to the cloud.
> 
> I use a "steam connected" account as opposed to an NK account. Not sure if the difference matters or not. I also tried the disconnecting internet method and it still crashes before the "choose a save" menu shows up. Not sure what you did specifically.
> 
> I had an old steam connected account and deleted it since it was flagged. The old one seemed to work with modifications regardless and never crashed. Not sure if newer accounts have a different "measure" so to speak.

I never messed with the different account types or anything. Is there no option to play offline? I'll look into this later... I wonder if there's some signature or something that's verified serverside.

**Comment by KirboC** [comment] 2022-09-11 15:38
> > > This has been a problem for a few months now, the fix is to disconnect from the internet the first time you put the re-compiled Profile.Save file into the folder. Once in the folder load up BTD6 and you'll notice it will load just fine. Exit the game then reconnect to the internet, then reopen BTD6 and it should work just fine, no crashing. You can even use the "Backup" function to back up the new save to the cloud.
> > 
> > 
> > I use a "steam connected" account as opposed to an NK account. Not sure if the difference matters or not. I also tried the disconnecting internet method and it still crashes before the "choose a save" menu shows up. Not sure what you did specifically.
> > I had an old steam connected account and deleted it since it was flagged. The old one seemed to work with modifications regardless and never crashed. Not sure if newer accounts have a different "measure" so to speak.
> 
> I never messed with the different account types or anything. Is there no option to play offline? I'll look into this later... I wonder if there's some signature or something that's verified serverside.

I don't think there's serverside verification because offline play would be impossible.

At first I thought it was looking for discrepancies between the cloud and local saves and if it detected something, it'd immediately roll back to the cloud save or crash.

 This doesn't seem to be the case because just decompiling and recompiling the Profile.Save without modifications and putting it in the folder will cause the game to crash. Going offline didn't seem to get around this (at least for me). That's just my personal observation.

**Comment by codeshaunted** [comment] 2022-12-16 05:51
Got some time to look into this, unable to reproduce and I am playing with a NinjaKiwi account.

**Comment by codeshaunted** [comment] 2023-03-02 19:27
Closing as stale, reopen with more information if problem persists.

**Closed as completed by codeshaunted** 2023-03-02 19:27 UTC
